### ISSUE TITLE
VAC TODO

### ISSUE THREAD

**Issue by adrn** [adrn/hq#2]
* [ ] Update VAC announcement form to show new files and status
* [x] You probably want to have an account at the Utah computers to stage your VAC into the sandbox (https://trac.sdss.org/wiki/DataArchive/Sandbox), and to be able to use scripts such as fitsverify (see below)
* [x] When you stage your VAC files into the sandbox, please choose an appropriate location and name. Please have a look at your relevant sandbox (APOGEE, eBOSS, MaNGA) by clicking on the links at the top of this wiki page, https://trac.sdss.org/wiki/DataArchive/Sandbox, and follow the naming convention of your sandbox. Make sure that your name is unique, and simple. If in doubt, ask me and Joel.
* [x] Your VAC files need to pass fitsverify. Please have a look at this wiki page for instructions, https://trac.sdss.org/wiki/DataArchive/DataRelease/Manual#Procedures, and do indicate on your VAC announcement form once your files have passed this test
* [x] Finally, your VAC needs a data model (see examples at https://data.sdss.org/datamodel/). This data model describes exactly what kind of data is stored in your VAC files. There is a template with a script available to generate a data model, that we strongly advise that you use. Instructions for generating a data model, and for placing it in the SVN structure, are available on this wiki page: https://trac.sdss.org/wiki/DataArchive/DataModel
* [ ] Once DR16 goes live, your VAC will appear in the list on this webpage: https://www.sdss.org/dr15/data_access/value-added-catalogs/. If you click on any of the VACs listed there, then you will see one or two paragraphs of text there. This is the text that we will copy from the abstract of your VAC announcement form. Make therefore sure that this abstract contains all the information that you want users of your VAC to have, and that it contains a link to any papers that describe your VAC. I will follow up with you about this in September.
